### ISSUE TITLE
H.264 encoded bit stream has redundant start code at beginning

### ISSUE THREAD

**Issue by dspmeng** [01org/libyami#634]
$ yamiencode -i test.yuv -o test.h264 -W 1920 -H 1080 --rcmode=CBR -b 4000 -c AVC -s I420
the encoded bit stream has a redundant start code at beginning as below.
00 00 00 01 00 00 00 01 67 4D 40 29 AB 40 3C 01 ....

Some stream analyzer (say Intel Video Pro Analyzer 2017 2.3.0.4478) can't recognize such stream as AVC.

**Comment by jsorg71** [comment]
Yes, I see this too.

**Comment by xuguangxin** [comment]
It caused by this line https://github.com/01org/libyami/blob/apache/encoder/vaapiencoder_h264.cpp#L696
Hi @lizhong1008 , could you help to fix it?

**Comment by xuguangxin** [comment]
unlike sps and pps, we do not always have sei. When we not have sei, this line will append 00 00 00 01 only

**Comment by lizhong1008** [comment]
@xuguangxin , yeah, I will send a patch to fix it today or tomorrow.

**Comment by lizhong1008** [comment]
@dspmeng , could you help to verify https://github.com/01org/libyami/pull/636?

**Comment by jsorg71** [comment]
Is this fixed?  I still get invalid encoded data but it may be another issue.

**Comment by xuguangxin** [comment]
Hi @jsorg71 
It should fixed by lizhong's patch, maybe you can share your command and stream for us.
thanks

**Comment by jsorg71** [comment]
It does fix the 2 start codes in a row at the beginning but  I still see 2 start codes per frame.
There is one at the beginning and one about 5 bytes in.
example

```
00000001 2E80800F 20000000 0141E0C0
...
```

**Comment by jsorg71** [comment]
You can reproduce this with yamiencode
yamiencode -i luke-642x390-nv12.yuv -W 642 -H 390 -c AVC -s NV12 -o luke.h264

**Comment by xuguangxin** [comment]
@lizhong1008 , could you help to  check this?thanks

**Comment by lizhong1008** [comment]
OK，I'll check it tomorrow.

**Comment by lizhong1008** [comment]
@jsorg71 It is not redundant start code, it is the necessary start code of each nal unit for Annex B.

**Comment by jsorg71** [comment]
hum, can you explain more?  Why is it necessary?
x264 does not do 2 start codes, nvenc does not do 2 start codes, older libyami does not do 2 start codes.  All annex B.
This is confusing my decoders that are expecting one start code per frame.

**Comment by jsorg71** [comment]
I provide a diff of what libyami used to do so we can compare.

**Comment by lizhong1008** [comment]
@jsorg71 can you share your encoded bitstream? Including both the laster yami encoded bistream, and older yami encoded bitstream.

**Comment by lizhong1008** [comment]
@jsorg71 the two start code you see it that, one is for the prefix Nal unit, the other is for slice data Nal unit. We add the prefix Nal Unit is for avc simulcast usage, simulcast request to set the priority_id in the prefix Nal Unit.

**Comment by xuguangxin** [comment]
Hi @lizhong1008 
I think this is the problem.According to h264 spec, decoder should drop unrecognized nal unit. However, in real world, the decoder may simply report error for this. Is it ok to remove prefix unit if it's normal h264  encoder?

**Comment by lizhong1008** [comment]
@xuguangxin simucast is for normal h264, not for svc-t.

**Comment by jsorg71** [comment]
What is simulcast?  and can this be an option?

**Comment by lizhong1008** [comment]
@jsorg71 
1. AVC simulcast means "multiple independent simulcast avc streams with different priority", they are avc streams with priority_id inserted in the Prefix Nal Unit.
2. Yes, seems same decoders have not  strictly follow h264 spec, and can not decode the Prefix Nal Unit. I am going to disable simulcast by default.

**Comment by jsorg71** [comment]
@lizhong1008 I'm trying to hack the code to see if this is the last issue(I really want to update my yami version on my servers).  If I just comment out the call to addPackedPrefixNalUnit in vaapiencoder_h264.cpp, will that turn it off?
https://github.com/01org/libyami/blob/apache/encoder/vaapiencoder_h264.cpp#L1920

**Comment by jsorg71** [comment]
@lizhong1008 I just went ahead and yes, that fixes it for me.
BTW, one of the decoders that was failing was a libyami decoder, just an older one.

**Comment by lizhong1008** [comment]
@jsorg71 , yes, I will sent a patch to disable h264 simulcast by default this week. Thanks for your comments.
